spring.application.name=BeLoyal
spring.datasource.url=jdbc:mysql://localhost:3306/be_loyal_db
spring.datasource.username=root
spring.datasource.password=Shpetim2005.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

#Setting up email server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=digimenu10@gmail.com
spring.mail.password=furz dvlq fref qqpz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Activation url
app.activation.base-url=https://nonprofit-mins-container-urban.trycloudflare.com/api/besahub/auth/activate

#Spring Security
app.jwt.secret=0mhDjGtR1N4cdamgyrGdb6rZyOssPqlaACTJDji5HKw=
app.jwt.access-ttl-minutes=1
app.refresh-ttl-days=30

# separate secret for ownership tokens (recommended)
app.ownership.jwt.secret=6ca5ad801e69ea6d987bc7ceacf29141

# minutes until ownership token expires
app.ownership.jwt.ttl-minutes=15

#This can matter for redirects, link building, and sometimes CORS expectations.
server.forward-headers-strategy=framework

#server config
server.address=0.0.0.0
server.port=8080