# GENERAL CONFIGURATION
spring.application.name=BeLoyal

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/be_loyal_db
spring.datasource.username=root
spring.datasource.password=Shpetim2005.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

# Setting up email server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=digimenu10@gmail.com
spring.mail.password=furz dvlq fref qqpz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Base URL (single definition)
app.base-url=https://defense-reunion-priced-movements.trycloudflare.com

# Activation url
app.activation.base-url=${app.base-url}

# Staff accept invitation url
app.staff.accept-invitation.base-url=${app.base-url}/api/besahub/auth/accept-invitation

# Spring Security
app.jwt.secret=0mhDjGtR1N4cdamgyrGdb6rZyOssPqlaACTJDji5HKw=
app.jwt.access-ttl-minutes=15
app.refresh-ttl-days=30

# Separate secret for ownership tokens (recommended)
app.ownership.jwt.secret=6ca5ad801e69ea6d987bc7ceacf29141

# Minutes until ownership token expires
app.ownership.jwt.ttl-minutes=15

# Minutes until reset password token expires
app.password.token.ttl-minutes=60
app.password.forget-email.base-url=${app.base-url}/forget-password

# This can matter for redirects, link building, and sometimes CORS expectations.
server.forward-headers-strategy=framework

# Server config
server.address=0.0.0.0
server.port=8080

# Local storage
app.storage.local.root=uploads
# Should be changed when using cloudflare tunnel
app.storage.public-base-url=${app.base-url}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# REDIS CONFIGURATION
spring.data.redis.host=localhost
spring.data.redis.port=6379

# For production
spring.data.redis.password=
spring.data.redis.database=0