# Liquibase Configuration Defaults
url=jdbc:mysql://localhost:3306/be_loyal_db
username=root
password=Shpetim2005.
driver=com.mysql.cj.jdbc.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
diffChangeLogFile=src/main/resources/db/changelog/changes/002-auto.xml
referenceUrl=hibernate:spring:com.shabanaj.beloyal?dialect=org.hibernate.dialect.MySQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
